# ultra-simple cloudformation template for nextflow on aws batch
# no frills, just what's needed to work
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal AWS Batch setup for Nextflow'

Parameters:
  # maximum cpu cores to prevent runaway costs
  MaxvCpus:
    Type: Number
    Default: 16
    Description: Maximum number of vCPUs

Resources:
  
  # ========== BASIC NETWORKING ==========
  
  # simple vpc - aws's private network for us  
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsHostnames: true
      EnableDnsSupport: true

  # subnet - where compute instances will live
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  # internet gateway - door to the internet
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  # attach gateway to vpc
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # route table - network directions
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  # route - send internet traffic to gateway
  Route:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  # connect subnet to route table
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

  # ========== SECURITY ==========
  
  # security group - basic firewall (outbound only)
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Batch security group'
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0'

  # ========== PERMISSIONS ==========
  
  # role for aws batch service
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  # role for compute instances
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: 
                  - 'arn:aws:s3:::bp-wgs-covaris-*'
                  - 'arn:aws:s3:::bp-wgs-covaris-*/*'

  # instance profile - wrapper for the role
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  # ========== COMPUTE ==========
  
  # compute environment - simplest possible
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      State: ENABLED
      ComputeEnvironmentName: nextflow-compute-env
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        MaxvCpus: !Ref MaxvCpus
        DesiredvCpus: 0
        InstanceTypes: 
          - optimal
        InstanceRole: !GetAtt InstanceProfile.Arn
        SecurityGroupIds:
          - !Ref SecurityGroup
        Subnets:
          - !Ref Subnet

  # job queue - where jobs wait
  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: nextflow-compute-queue
      State: ENABLED
      Priority: 100
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref ComputeEnvironment

# outputs - useful info after creation
Outputs:
  ComputeEnvironment:
    Description: 'Compute environment name'
    Value: !Ref ComputeEnvironment
  
  JobQueue:
    Description: 'Job queue name'
    Value: !Ref JobQueue
