name: Run Nextflow Pipeline on AWS

on:
  workflow_dispatch:
    inputs:
      input_s3_path:
        description: 'S3 path to input FASTQ files'
        required: true
        default: 's3://bp-wgs-covaris-input-data/samples'
      output_s3_path:
        description: 'S3 path for results'
        required: true
        default: 's3://bp-wgs-covaris-nextflow-results/results'
      aws_region:
        description: 'AWS region (e.g., us-east-1, us-east-2, eu-west-1)'
        required: true
      nextflow_version:
        description: 'Nextflow version to use'
        required: false
        default: '23.10.1'

jobs:
  run-nextflow:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Install Nextflow
        run: |
          wget -qO- https://get.nextflow.io | bash -s -- -version ${{ github.event.inputs.nextflow_version }}
          sudo mv nextflow /usr/local/bin/
          chmod +x /usr/local/bin/nextflow

      - name: Validate AWS setup
        run: |
          aws sts get-caller-identity
          aws batch describe-compute-environments --region ${{ github.event.inputs.aws_region }}

      - name: Debug S3 input files
        run: |
          echo "Listing contents of input S3 bucket:"
          aws s3 ls ${{ github.event.inputs.input_s3_path }}/ --recursive
          echo ""
          echo "Looking specifically for fastq.gz files:"
          aws s3 ls ${{ github.event.inputs.input_s3_path }}/ --recursive | grep "\.fastq\.gz" || true
          echo ""
          echo "Total file count:"
          aws s3 ls ${{ github.event.inputs.input_s3_path }}/ --recursive | wc -l

      - name: Debug Nextflow parameters
        run: |
          echo "Input S3 path: '${{ github.event.inputs.input_s3_path }}'"
          echo "Output S3 path: '${{ github.event.inputs.output_s3_path }}'"
          echo "AWS region: '${{ github.event.inputs.aws_region }}'"
          echo "Nextflow version: '${{ github.event.inputs.nextflow_version }}'"

      - name: Confirm S3 access is working
        run: |
          echo "S3 access already confirmed in previous steps - skipping complex test script"

      # Fusion / Wave integration
      - name: Export Seqera/Tower Token
        run: echo "TOWER_ACCESS_TOKEN=${{ secrets.TOWER_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Run Nextflow pipeline (with Fusion)
        run: |
          echo "About to run this Nextflow command with Fusion enabled:"
          echo "nextflow run main.nf -profile aws --input_dir \"${{ github.event.inputs.input_s3_path }}\" --outdir \"${{ github.event.inputs.output_s3_path }}\" --aws_region \"${{ github.event.inputs.aws_region }}\" -with-report nextflow_report.html -with-timeline timeline.html -with-dag flowchart.html -with-fusion"
          echo ""
          
          nextflow run main.nf \
            -profile aws \
            --input_dir "${{ github.event.inputs.input_s3_path }}" \
            --outdir "${{ github.event.inputs.output_s3_path }}" \
            --aws_region "${{ github.event.inputs.aws_region }}" \
            -with-report nextflow_report.html \
            -with-timeline timeline.html \
            -with-dag flowchart.html \
            -with-fusion

      - name: Upload Nextflow reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nextflow-reports
          path: |
            nextflow_report.html
            timeline.html
            flowchart.html
            .nextflow.log

      - name: Cleanup
        if: always()
        run: |
          rm -rf work/ .nextflow*
